version: "3.9"

services:
  ubuntu-sshx:
    image: ubuntu:22.04
    container_name: ubuntu-sshx
    restart: unless-stopped
    stdin_open: true
    tty: true

    # Mount KVM nếu host có hỗ trợ
    devices:
      - /dev/kvm:/dev/kvm

    # Cài sshx + chạy luôn khi container start
    command: >
      bash -c "apt-get update &&
               apt-get install -y curl wget iputils-ping &&
               curl -sSf https://sshx.io/get | sh -s run"

    ports:
      - "3000:3000"

    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8G
        reservations:
          cpus: "2.0"
          memory: 4G
